# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e229bbabfac164daf0e11a3c675d367ee0d5170288534edef2ddef91d2fc777a1dde5a6a433f0f6f17dfd057ef361defa19a5c1459c34cbfb4c2ae36c0bf7b6f

test:
  secret_key_base: a540888e10e20e410742f6f6bc22a4c6fa1dd3da9c926e7c062c675d8967db1f30409ba2b01db314be1f467023ac8e0a58d90488bbb3dbe822560b1ac94fd0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
